# Generated by Django 3.1.7 on 2021-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DogMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_like_receiver', models.ManyToManyField(related_name='_dogmatch_dog_like_receiver_+', to='matchingapp.Dog')),
                ('dog_like_sender', models.ManyToManyField(related_name='_dogmatch_dog_like_sender_+', to='matchingapp.Dog')),
            ],
        ),
    ]
