# Generated by Django 3.1.7 on 2021-04-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogmatch',
            name='dog_like_receiver',
        ),
        migrations.AddField(
            model_name='dogmatch',
            name='dog_like_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_like_receiver+', to='matchingapp.dog'),
        ),
        migrations.RemoveField(
            model_name='dogmatch',
            name='dog_like_sender',
        ),
        migrations.AddField(
            model_name='dogmatch',
            name='dog_like_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_like_sender+', to='matchingapp.dog'),
        ),
    ]
